import { FighterConfig, ArenaConfig } from '../types/fighter';

export const FIGHTERS: Record<string, FighterConfig> = {
  gojo: {
    id: 'gojo',
    name: 'Gojo Satoru (Ngũ Điều Ngộ)',
    title: 'Đệ Nhất Chú Thuật Sư · Lục Nhãn Vô Hạ',
    series: 'Jujutsu Kaisen',
    themeColor: '#38bdf8', // Cyan Azure
    secondaryColor: '#c084fc', // Hollow Purple
    avatarUrl: '/src/assets/images/fighter_gojo_orb_1790609180617.jpg',
    maxHp: 1200, // Cân bằng: Tương đương Sukuna (1250) và SJW (1150)
    maxEnergy: 100,
    maxBurst: 100,
    weight: 1.15,
    baseSpeed: 17.5, // Nhanh nhẹn cân đối, không vượt quá Sans (21)
    defense: 0.90, // Phòng thủ chuẩn (nhận 90% sát thương, không còn 82%)
    radius: 46,
    lore: 'Đệ nhất Chú thuật sư, sở hữu Vô Hạ Hạn Thuật thức tạo lá chắn thời gian ngắn, Hắc Thiểm thần tốc và đôi mắt Lục Nhãn giúp hồi phục Chú Lực nhanh nhẹn.',
    skills: {
      skill1: {
        id: 'gojo_infinity',
        name: 'Vô Hạ Hạn (Infinity Barrier)',
        vietnameseName: 'Vô Hạ Hạn Hộ Thể',
        description: 'Kích hoạt màng bảo hộ Vô Hạ Hạn trong 1.3s: Chặn sát thương va chạm và tạo xung lực đẩy lùi đối thủ!',
        manaCost: 35,
        burstCost: 0,
        cooldown: 210,
        damage: 28,
        knockbackPower: 26,
        color: '#38bdf8',
        accentColor: '#ffffff',
        soundType: 'impact',
      },
      skill2: {
        id: 'gojo_red_blue',
        name: 'Thuật Thức Thuận & Đảo (Red & Blue)',
        vietnameseName: 'Xích Hút & Thương Đẩy',
        description: 'Tạo hố đen không gian hút đối thủ từ xa và bộc phát xung kích gây 36 sát thương!',
        manaCost: 35,
        burstCost: 0,
        cooldown: 180,
        damage: 36,
        knockbackPower: 32,
        color: '#f43f5e',
        accentColor: '#0284c7',
        soundType: 'explosion',
      },
      skill3: {
        id: 'gojo_black_flash',
        name: 'Hắc Thiểm (Black Flash)',
        vietnameseName: 'Hắc Thiểm Tia Chớp Đen',
        description: 'Bộc phát tia sét không gian đen kịt, gây 44 sát thương và đưa Gojo vào trạng thái Thức Tỉnh tăng tốc!',
        manaCost: 35,
        burstCost: 0,
        cooldown: 180,
        damage: 44,
        knockbackPower: 36,
        color: '#1e1b4b',
        accentColor: '#38bdf8',
        soundType: 'impact',
      },
      ultimate: {
        id: 'gojo_purple',
        name: 'HƯ THỨC: TỬ (Hollow Purple)',
        vietnameseName: 'HƯ THỨC: TỬ (HOLLOW PURPLE)',
        description: 'Hợp nhất Xích và Thương phóng ra siêu cầu lượng tử tím càn quét đấu trường với 100 sát thương!',
        manaCost: 0,
        burstCost: 100,
        cooldown: 600,
        damage: 100,
        knockbackPower: 45,
        color: '#9333ea',
        accentColor: '#e879f9',
        soundType: 'hollow_purple',
      },
    },
  },

  sukuna: {
    id: 'sukuna',
    name: 'Ryomen Sukuna (Lưỡng Diện Túc Na)',
    title: 'Ngự Ma Thần Vương · Vua Lời Nguyền',
    series: 'Jujutsu Kaisen',
    themeColor: '#ef4444', // Crimson Red
    secondaryColor: '#f97316', // Orange Fire
    avatarUrl: '/src/assets/images/fighter_sukuna_orb_1790609197984.jpg',
    maxHp: 1250,
    maxEnergy: 100,
    maxBurst: 100,
    weight: 1.25,
    baseSpeed: 17,
    defense: 0.92,
    radius: 46,
    lore: 'Ngự Ma Thần Vương ngàn năm, reo rắc nỗi kinh hoàng với trảm kích vô ảnh xé rách không gian và ngọn lửa hủy diệt Fuga.',
    skills: {
      skill1: {
        id: 'sukuna_dismantle',
        name: 'Trảm Kích: Giải & Bát (Dismantle)',
        vietnameseName: 'Trảm Kích Giải & Bát',
        description: 'Phóng ra hàng loạt đường chém đỏ rực xé toạc không gian, cắt ngang quả bóng đối phương và gây chấn động.',
        manaCost: 30,
        burstCost: 0,
        cooldown: 160,
        damage: 32,
        knockbackPower: 22,
        color: '#dc2626',
        accentColor: '#fee2e2',
        soundType: 'dismantle',
      },
      skill2: {
        id: 'sukuna_fuga',
        name: 'Hỏa Tiễn: Fuga (Kamino Open)',
        vietnameseName: 'Hỏa Tiễn Fuga: Khai Mở',
        description: 'Khai mở mũi tên lửa thần thánh thiêu rụi toàn bộ quỹ đạo bay, tăng 300% tốc độ lao thẳng vào mục tiêu.',
        manaCost: 45,
        burstCost: 0,
        cooldown: 220,
        damage: 45,
        knockbackPower: 35,
        color: '#ea580c',
        accentColor: '#facc15',
        soundType: 'explosion',
      },
      skill3: {
        id: 'sukuna_world_slash',
        name: 'Thế Giới Trảm (World Cutting Slash)',
        vietnameseName: 'Trảm Kích Cắt Không Gian',
        description: 'Mở rộng mục tiêu thuật thức chém đứt chính không gian và tọa độ đối thủ đang đứng, xuyên phá mọi lớp giáp!',
        manaCost: 40,
        burstCost: 0,
        cooldown: 200,
        damage: 42,
        knockbackPower: 36,
        color: '#b91c1c',
        accentColor: '#fca5a5',
        soundType: 'dismantle',
      },
      ultimate: {
        id: 'sukuna_shrine',
        name: 'PHỤC MA NGỰ THẦN ĐIỆN (Malevolent Shrine)',
        vietnameseName: 'MỞ RỘNG LÃNH ĐỊA: PHỤC MA NGỰ THẦN ĐIỆN',
        description: 'Mở rộng lãnh địa đền quỷ, giáng xuống cơn bão vô số nhát trảm kích liên hoàn đập nát đối phương trong lồng sắt!',
        manaCost: 0,
        burstCost: 100,
        cooldown: 600,
        damage: 105,
        knockbackPower: 48,
        color: '#991b1b',
        accentColor: '#f87171',
        soundType: 'dismantle',
      },
    },
  },

  sjw: {
    id: 'sjw',
    name: 'Sung Jin-Woo (Thành Chấn Vũ)',
    title: 'Quân Vương Bóng Tối · Thợ Săn Rank S',
    series: 'Solo Leveling',
    themeColor: '#8b5cf6', // Violet Shadow
    secondaryColor: '#38bdf8', // Neon Blue
    avatarUrl: '/src/assets/images/fighter_sjw_orb_1790609218900.jpg',
    maxHp: 1150,
    maxEnergy: 100,
    maxBurst: 100,
    weight: 1.05,
    baseSpeed: 18,
    defense: 0.88,
    radius: 46,
    lore: 'Quân vương bóng tối điều khiển sinh tử, sở hữu ngự thuật sát thủ tàng hình và đội quân bóng ma trỗi dậy từ cõi chết.',
    skills: {
      skill1: {
        id: 'sjw_shadow_dash',
        name: 'Thần Tốc Trảm (Shadow Dagger Rush)',
        vietnameseName: 'Thần Tốc Đột Kích',
        description: 'Biến vào hư không và xuất hiện đập vào gáy đối phương với vận tốc ánh sáng kèm hiệu ứng tàn ảnh rực rỡ.',
        manaCost: 30,
        burstCost: 0,
        cooldown: 140,
        damage: 30,
        knockbackPower: 28,
        color: '#7c3aed',
        accentColor: '#67e8f9',
        soundType: 'impact',
      },
      skill2: {
        id: 'sjw_arise',
        name: 'TRỖI DẬY! (ARISE - Binh Đoàn Bóng Tối)',
        vietnameseName: 'TRỖI DẬY (ARISE!)',
        description: 'Triệu hồi 3 quả cầu bóng tối hắc ám (Igris, Tank, Iron) cùng nảy quanh sàn đập hội đồng kẻ địch!',
        manaCost: 50,
        burstCost: 0,
        cooldown: 240,
        damage: 35,
        knockbackPower: 20,
        color: '#6d28d9',
        accentColor: '#a78bfa',
        soundType: 'arise',
      },
      skill3: {
        id: 'sjw_rulers_authority',
        name: 'Bạo Tác Chưởng (Ruler\'s Authority)',
        vietnameseName: 'Long Uy Kẻ Thống Trị',
        description: 'Bàn tay vô hình của Quân Vương vươn xa kẹp chặt quả bóng đối thủ và đập mạnh xuống sàn đấu!',
        manaCost: 35,
        burstCost: 0,
        cooldown: 190,
        damage: 38,
        knockbackPower: 32,
        color: '#7e22ce',
        accentColor: '#c084fc',
        soundType: 'impact',
      },
      ultimate: {
        id: 'sjw_monarch_domain',
        name: 'LÃNH ĐỊA QUÂN VƯƠNG (Monarch Domain)',
        vietnameseName: 'LÃNH ĐỊA QUÂN VƯƠNG BÓNG TỐI',
        description: 'Bóng tối nuốt chửng toàn bộ võ đài, ngưng đọng đối phương và triệu hồi thanh Cự Kiếm Vực Thẳm bổ xuống nát sàn!',
        manaCost: 0,
        burstCost: 100,
        cooldown: 600,
        damage: 100,
        knockbackPower: 46,
        color: '#4c1d95',
        accentColor: '#38bdf8',
        soundType: 'hollow_purple',
      },
    },
  },

  sans: {
    id: 'sans',
    name: 'Sans the Skeleton',
    title: 'Người Phán Xử Cuối Cùng · 1 HP Né Tránh',
    series: 'Undertale',
    themeColor: '#0284c7', // Sky Cyan
    secondaryColor: '#facc15', // Bad Time Yellow Eye
    avatarUrl: '/src/assets/images/sans_avatar_1790610948593.jpg',
    maxHp: 1, // Undertale Canon: Đúng 1 HP!
    maxEnergy: 100, // Thể lực né tránh (Stamina)
    maxBurst: 100,
    weight: 0.92,
    baseSpeed: 21, // Siêu nhanh nhẹn và lướt né
    defense: 1.0, // 1 HP, 1 DEF
    radius: 45,
    lore: 'Bộ xương lười biếng nhưng nguy hiểm nhất thế giới ngầm. Sở hữu đúng 1 HP duy nhất nhưng tự động né tránh 100% mọi đòn đánh và chiêu thức khi còn Thể Lực (Năng lượng). Nhưng khi cạn Thể Lực (0 MP), Sans sẽ kiệt sức thở dốc và bị đánh trúng chết ngay lập tức!',
    skills: {
      skill1: {
        id: 'sans_gaster_blaster',
        name: 'Gaster Blaster (Đầu Lâu Ma Pháp)',
        vietnameseName: 'Đầu Lâu Gaster Blaster',
        description: 'Triệu hồi đầu lâu quái thú Gaster Blaster phóng chùm tia laser tử thần quét dọc đấu trường, gây sát thương Karma xuyên thấu!',
        manaCost: 25,
        burstCost: 0,
        cooldown: 150,
        damage: 38,
        knockbackPower: 34,
        color: '#38bdf8',
        accentColor: '#ffffff',
        soundType: 'gaster_blaster',
      },
      skill2: {
        id: 'sans_blue_soul',
        name: 'Linh Hồn Xanh (Blue Soul Gravity)',
        vietnameseName: 'Linh Hồn Xanh (Trọng Lực)',
        description: 'Bẻ cong tâm hồn đối thủ thành màu xanh lam, cưỡng chế trọng lực nện đập dữ dội vào tường võ đài liên hồi!',
        manaCost: 20,
        burstCost: 0,
        cooldown: 160,
        damage: 35,
        knockbackPower: 40,
        color: '#2563eb',
        accentColor: '#60a5fa',
        soundType: 'impact',
      },
      skill3: {
        id: 'sans_bone_wave',
        name: 'Rừng Xương Phán Quyết (Bone Storm)',
        vietnameseName: 'Rừng Xương Phán Quyết',
        description: 'Triệu hồi hàng loạt gai xương trắng sắc nhọn trồi lên chặn đường lao và cào rách đối thủ với sát thương Karma liên hồi!',
        manaCost: 25,
        burstCost: 0,
        cooldown: 170,
        damage: 40,
        knockbackPower: 30,
        color: '#e0f2fe',
        accentColor: '#38bdf8',
        soundType: 'impact',
      },
      ultimate: {
        id: 'sans_bad_time',
        name: 'THỜI KHẮC TỒI TỆ (You\'re Gonna Have A Bad Time)',
        vietnameseName: 'PHÁN QUYẾT TỘI LỖI (MEGALOVANIA)',
        description: 'Mắt ma thuật rực lửa lam-vàng! Triệu hồi dàn Gaster Blaster 360 độ và bão xương tử thần xả luồng năng lượng hủy diệt khắp đấu trường!',
        manaCost: 0,
        burstCost: 100,
        cooldown: 550,
        damage: 115,
        knockbackPower: 52,
        color: '#0284c7',
        accentColor: '#facc15',
        soundType: 'gaster_blaster',
      },
    },
  },
};

export const ARENAS: ArenaConfig[] = [
  {
    id: 'judgment_hall',
    name: 'Last Corridor (Judgment Hall)',
    vietnameseName: 'Hành Lang Phán Xét Cuối Cùng',
    backgroundUrl: '/src/assets/images/arena_judgment_hall_1790610997635.jpg',
    ambientLight: 'rgba(250, 204, 21, 0.12)',
    wallBounciness: 0.96,
  },
  {
    id: 'cyber_dojo',
    name: 'Neo Tokyo Cyber Colosseum',
    vietnameseName: 'Đấu Trường Năng Lượng Cyber',
    backgroundUrl: '/src/assets/images/arena_cyber_dojo_1790608701315.jpg',
    ambientLight: 'rgba(56, 189, 248, 0.15)',
    wallBounciness: 0.95,
  },
  {
    id: 'flame_ruins',
    name: 'Volcanic Ruin Ring',
    vietnameseName: 'Võ Đài Hỏa Ngục Viêm Ma',
    backgroundUrl: '/src/assets/images/arena_flame_ruins_1790608716122.jpg',
    ambientLight: 'rgba(249, 115, 22, 0.2)',
    wallBounciness: 0.92,
  },
];
